### PR TITLE
minio add podmonitor and update metrics path

### PR DESCRIPTION
**Pull request by locustbaby**
## What this PR does / why we need it:
1. update the metrics path from `/minio/prometheus/metrics` to `/minio/v2/metrics/cluster`
2. add podMonitor for minio

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Review by LoveEachDay — CHANGES_REQUESTED** [review]
We'd create a secret when podMonitor is enabled, check the file `post-install-prometheus-metrics-job.yaml`

**Comment by LoveEachDay** [comment]
And you should also rebase you commits into one.

**Comment by locustbaby** [comment]
I didn't find any args about `MINIO_PROMETHEUS_AUTH_TYPE` so I think the default `auth type` of metrics is `jwt`.

If `jwt` mode, the `post-install-prometheus-metrics-job.yaml` must be run, but it relies on RBAC.
when I made a test of helm install with args `--set metrics.serviceMonitor.enabled=true  --set serviceAccount.create=false`, I found it failed because the other three RBAC yamls relies on `serviceAccount.create`.

So I modify all the `post-install-xxx.yaml` so that only relies on whether you enable the `servicemonitor/podmonitor`

**Review by LoveEachDay — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
