### PR TITLE
attu deployment tolerations fix

### PR DESCRIPTION
**Pull request by AliDotS**
Signed-off-by: Ali Salimi <salimiali28@gmail.com>

When using tolerations, the generated manifest can't be applied.
In attu-deployment tolerations is placed inside spec.template but it should be inside spec.template.spec

- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [ ] PR only contains changes for one chart

### CODE REVIEW

**Comment by LoveEachDay** [comment]
@AliDotS Good catch.
You should bump the chart version to `3.0.11` , in `charts/milvus/Chart.yaml`.

**Comment by AliDotS** [comment]
Sorry for the delay.
I see the chart has been updated. I updated the PR and also bumped the chart version to 3.0.14.

**Comment by LoveEachDay** [comment]
@AliDotS Please bump the chart version to fix the conflict.

**Comment by AliDotS** [comment]
Updated

**Review by LoveEachDay — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
