### PR TITLE
[pulsar] Bump pulsar to 2.9.4 in requirements.yaml and requirements.lock

### PR DESCRIPTION
**Pull request by claudio-vellage**
## What this PR does / why we need it:
I think it's beneficial to update the chart in any case, but in this particular case, I've contributed changes to the pulsar repository, so it's possible to specify a `selector` for the `volumeClaimTemplates`. This allows to use statically provisioned volumes with pulsar, which makes it possible to easily persist the pulsar data between cluster recreation.

For more information, I can recommend reading the related "motivation" section from the openshift (it also applies to k8s) documentation: https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/selector_label_binding.html#selector-label-volume-motivation

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Comment by haorenfsa** [comment]
Hi, I think the upgrade of helm chart itself is great, as long as it's compatitable with the current stable image version we're using, which 2.8.2. Have you test it? 

By the way, it also resolves #314  

/cc @LoveEachDay

**Comment by LoveEachDay** [comment]
@claudio-vellage Thanks for you contribution. 

First, you cannot just manually update the version in `charts/milvus/requirements.lock`, you need first update the version in `charts/milvus/requirements.yaml`, then run `helm dependency update` to update the `requirements.lock` files and replace the charts file under `charts/milvus/charts` directory.

Second, we need fully test the pulsar 2.9.4 before we can merge this pr.

**Comment by claudio-vellage** [comment]
@LoveEachDay can you do the tests from your end? I think there should be no issue, because this is not an upgrade in pulsar major version? If you can't run the tests, how am I supposed to test it?

**Comment by haorenfsa** [comment]
@claudio-vellage We have to run through quite a lot system tests & benchmarks before we merge it.  But the test team is busy with the coming 2.2.0 release. So I'm sorry to say for now there's no schedule about it.

If you are to use the new chart, you can deploy it alone with the `values` under `.pulsar fields` defined in [charts/milvus/values.yaml](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml#L681) 
(eg: if a value is `pulsar.fieldA`, when deploying pular with new chart alone, you should set the value in `.fieldA`)

And then install milvus with `pulsar.enable` set to `false` & enable the `externalPulsar` with address correctly set [charts/milvus/values.yaml](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml#L1017)

```yaml
# milvus value file
pulsar:
  enabled: false
externalPulsar:
  enabled: true
  host: <your pulsar host here>
  port: 6650
```

**Comment by haorenfsa** [comment]
> @claudio-vellage Thanks for you contribution.
> 
> First, you cannot just manually update the version in `charts/milvus/requirements.lock`, you need first update the version in `charts/milvus/requirements.yaml`, then run `helm dependency update` to update the `requirements.lock` files and replace the charts file under `charts/milvus/charts` directory.
> 
> Second, we need fully test the pulsar 2.9.4 before we can merge this pr.

If we just upgrade the chart without changing pulsar images in `values.yaml`, it seems to be Okey if pulsar can still be deployed correctly?

**Pull request closed without merging**
