### PR TITLE
Remove hpa for milvus proxy, query node, index node and data node

### PR DESCRIPTION
**Pull request by LoveEachDay**
Signed-off-by: Edward Zeng <jie.zeng@zilliz.com>

## What this PR does / why we need it:
/cc @zwd1208 @Bennu-Li 

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] Chart Version bumped
- [x ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [ ] PR only contains changes for one chart

### CODE REVIEW

**Comment by scipe** [comment]
@LoveEachDay hey. Why we decided to delete HPA?

**Comment by LoveEachDay** [comment]
> 

@scipe HPA is great for stateless applications. Our nodes have some internal data logic which make nodes not stateless. You can manually increase the number of replicas to adapt to the increase throughput. But automatically increase/decrease the number of replicas according to the cpu usage via HPA may not receive any performance gain. 

So for now, we decide to remove the HPA from milvus-helm chart. We'll implement a milvus hpa based on message queue consumption in future version.

**Comment by scipe** [comment]
@LoveEachDay thanks for you answer. It make me sense. Will try to use Keda with queue size to scale my index nodes.

**Pull request merged**
